// Property data
export const PROPERTIES_DATA = [
  {
    id: 1,
    title: "Luxury 3 BHK Apartment with Modern Amenities",
    customPropertyName: "Esto Arkis",
    projectName: "Esto Arkis Tower A",
    city: "Mumbai",
    locality: "Andheri West",
    landmark: "Near Infinity Mall",
    addressText: "Andheri West, Mumbai, Maharashtra 400053, India",
    coordinates: {
      lat: 19.1136,
      lng: 72.8697,
    },
    propertyType: "apartment",
    listingType: "sale",
    bedrooms: "3",
    bathrooms: "3",
    pricing: [
      {
        type: "asking_price",
        unit: "total",
        value: "32500000",
      },
    ],
    carpetArea: "1450",
    superArea: "1850",
    facing: "north",
    floorNumber: "12",
    totalFloors: "25",
    unitNumber: "1205",
    towerName: "A",
    furnishingStatus: "semi",
    possessionStatus: "ready",
    ageOfProperty: "2",
    ownershipType: "freehold",
    isGated: true,
    view: "city_view",
    mediaData: [
      {
        url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop",
        type: "image",
        title: "Living Room",
      },
      {
        url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
        type: "image",
        title: "Bedroom",
      },
      {
        url: "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=800&h=600&fit=crop",
        type: "image",
        title: "Kitchen",
      },
    ],
    features: [
      "swimming_pool",
      "gym",
      "jogging_track",
      "cctv_surveillance",
      "power_backup",
      "clubhouse",
    ],
    amenities: [
      "balcony",
      "modular_kitchen",
      "servant_room",
    ],
    developer: "ESTO GROUP",
    verificationStatus: "VERIFIED",
    isPriceNegotiable: true,
    showMapExact: false,
    description:
      "Spacious 3 BHK apartment in prime Andheri West location with modern amenities and excellent connectivity.",
  },
  {
    id: 2,
    title: "Premium 4 BHK Apartment with Garden View",
    customPropertyName: "Shree Gopaldham",
    projectName: "Shree Gopaldham Phase 2",
    city: "Mumbai",
    locality: "Kandivali West",
    landmark: "Near Thakur Mall",
    addressText: "Kandivali West, Mumbai, Maharashtra 400067, India",
    coordinates: {
      lat: 19.2074,
      lng: 72.832,
    },
    propertyType: "apartment",
    listingType: "sale",
    bedrooms: "4",
    bathrooms: "4",
    pricing: [
      {
        type: "asking_price",
        unit: "total",
        value: "48500000",
      },
    ],
    carpetArea: "1850",
    superArea: "2300",
    facing: "east",
    floorNumber: "8",
    totalFloors: "18",
    unitNumber: "802",
    towerName: "B",
    furnishingStatus: "semi",
    possessionStatus: "ready",
    ageOfProperty: "1",
    ownershipType: "freehold",
    isGated: true,
    view: "garden_view",
    mediaData: [
      {
        url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop",
        type: "image",
        title: "Exterior View",
      },
      {
        url: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop",
        type: "image",
        title: "Living Area",
      },
      {
        url: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&h=600&fit=crop",
        type: "image",
        title: "Master Bedroom",
      },
    ],
    features: [
      "swimming_pool",
      "gym",
      "children_play_area",
      "landscaped_gardens",
      "cctv_surveillance",
      "power_backup",
      "clubhouse",
      "sports_facilities",
    ],
    amenities: [
      "balcony",
      "modular_kitchen",
      "servant_room",
      "study_room",
      "private_terrace",
    ],
    developer: "JEEVEE INFRA",
    verificationStatus: "VERIFIED",
    isPriceNegotiable: false,
    showMapExact: false,
    reraIds: [{ id: "P51700018456" }],
    description:
      "Luxurious 4 BHK apartment with garden view in well-maintained gated community with world-class amenities.",
  },
  {
    id: 3,
    title: "Modern 2 BHK with Premium Finishes",
    customPropertyName: "Serenova",
    projectName: "Kolte Patil Serenova",
    city: "Mumbai",
    locality: "Andheri West",
    landmark: "Near DN Nagar Metro",
    addressText: "Andheri West, Mumbai, Maharashtra 400058, India",
    coordinates: {
      lat: 19.12,
      lng: 72.86,
    },
    propertyType: "apartment",
    listingType: "sale",
    bedrooms: "2",
    bathrooms: "2",
    pricing: [
      {
        type: "asking_price",
        unit: "total",
        value: "38000000",
      },
    ],
    carpetArea: "1100",
    superArea: "1400",
    facing: "west",
    floorNumber: "15",
    totalFloors: "28",
    unitNumber: "1503",
    towerName: "C",
    furnishingStatus: "fully",
    possessionStatus: "ready",
    ageOfProperty: "0",
    ownershipType: "freehold",
    isGated: true,
    view: "sea_view",
    isNewProperty: true,
    mediaData: [
      {
        url: "https://images.unsplash.com/photo-1565402170291-8491f14678db?w=800&h=600&fit=crop",
        type: "image",
        title: "Living Room",
      },
      {
        url: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop",
        type: "image",
        title: "Bedroom View",
      },
      {
        url: "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&h=600&fit=crop",
        type: "image",
        title: "Balcony",
      },
      {
        url: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&h=600&fit=crop",
        type: "image",
        title: "Kitchen",
      },
    ],
    features: [
      "swimming_pool",
      "gym",
      "jogging_track",
      "cctv_surveillance",
      "power_backup",
      "clubhouse",
      "rainwater_harvesting",
      "solar_panels",
    ],
    amenities: [
      "balcony",
      "modular_kitchen",
      "ac",
      "wifi",
    ],
    smartHomeDevices: [
      "smart_thermostat",
      "video_doorbell",
      "smart_lights",
      "home_automation_system",
    ],
    developer: "KOLTE PATIL",
    verificationStatus: "VERIFIED",
    isPriceNegotiable: true,
    showMapExact: false,
    reraIds: [{ id: "P51700032856" }],
    description:
      "Brand new 2 BHK apartment with smart home features and stunning sea view. Ready to move in with premium finishes.",
  },
  {
    id: 4,
    title: "Affordable 2 BHK in Prime Location",
    customPropertyName: "Raghav Ananta",
    projectName: "Raghav Ananta Residency",
    city: "Mumbai",
    locality: "Vikhroli",
    landmark: "Near Godrej Memorial Hospital",
    addressText: "Vikhroli, Mumbai, Maharashtra 400079, India",
    coordinates: {
      lat: 19.1107,
      lng: 72.9253,
    },
    propertyType: "apartment",
    listingType: "sale",
    bedrooms: "2",
    bathrooms: "2",
    pricing: [
      {
        type: "asking_price",
        unit: "total",
        value: "15500000",
      },
    ],
    carpetArea: "780",
    superArea: "950",
    facing: "north",
    floorNumber: "6",
    totalFloors: "12",
    unitNumber: "604",
    towerName: "A",
    furnishingStatus: "unfurnished",
    possessionStatus: "ready",
    ageOfProperty: "3",
    ownershipType: "freehold",
    isGated: true,
    view: "park_view",
    mediaData: [
      {
        url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&h=600&fit=crop",
        type: "image",
        title: "Building View",
      },
      {
        url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
        type: "image",
        title: "Living Space",
      },
    ],
    features: [
      "children_play_area",
      "cctv_surveillance",
      "power_backup",
      "landscaped_gardens",
    ],
    amenities: ["balcony"],
    developer: "RAGHAV BUILDERS",
    verificationStatus: "VERIFIED",
    isPriceNegotiable: true,
    showMapExact: false,
    description:
      "Well-maintained 2 BHK apartment in family-friendly locality with good connectivity to Eastern Express Highway.",
  },
  {
    id: 5,
    title: "Ultra Luxury 4 BHK with Sea View",
    customPropertyName: "Shapoorji Minerva",
    projectName: "Shapoorji Pallonji Minerva",
    city: "Mumbai",
    locality: "Mahalaxmi",
    landmark: "Near Mahalaxmi Race Course",
    addressText: "Mahalaxmi, Mumbai, Maharashtra 400034, India",
    coordinates: {
      lat: 18.9826,
      lng: 72.8233,
    },
    propertyType: "apartment",
    listingType: "sale",
    bedrooms: "4",
    bathrooms: "5",
    pricing: [
      {
        type: "asking_price",
        unit: "total",
        value: "145000000",
      },
    ],
    carpetArea: "3200",
    superArea: "4100",
    facing: "west",
    floorNumber: "22",
    totalFloors: "35",
    unitNumber: "2201",
    towerName: "Sky Villa",
    furnishingStatus: "fully",
    possessionStatus: "ready",
    ageOfProperty: "1",
    ownershipType: "freehold",
    isGated: true,
    view: "sea_view",
    petFriendly: true,
    mediaData: [
      {
        url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
        type: "image",
        title: "Sea View Living Room",
      },
      {
        url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
        type: "image",
        title: "Master Suite",
      },
      {
        url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
        type: "image",
        title: "Private Terrace",
      },
      {
        url: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&h=600&fit=crop",
        type: "image",
        title: "Designer Kitchen",
      },
      {
        url: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop",
        type: "image",
        title: "Balcony View",
      },
    ],
    features: [
      "swimming_pool",
      "gym",
      "spa",
      "jogging_track",
      "cctv_surveillance",
      "power_backup",
      "concierge_service",
      "valet_parking",
      "clubhouse",
      "sports_facilities",
      "party_hall",
    ],
    amenities: [
      "private_terrace",
      "modular_kitchen",
      "servant_room",
      "study_room",
      "home_theater",
      "wine_cellar",
      "ac",
      "wifi",
    ],
    smartHomeDevices: [
      "smart_thermostat",
      "video_doorbell",
      "smart_lights",
      "cctv_cameras",
      "smart_curtains",
      "home_automation_system",
      "smart_switches",
    ],
    flooringTypes: ["Italian Marble", "Wooden"],
    fireSafety: true,
    hasEmergencyExit: true,
    developer: "SHAPOORJI PALLONJI",
    verificationStatus: "VERIFIED",
    isPriceNegotiable: false,
    showMapExact: false,
    reraIds: [{ id: "P51800015623" }],
    description:
      "Exquisite 4 BHK sky villa with panoramic sea views, premium Italian marble flooring, and state-of-the-art smart home automation. Ultra-luxury living at its finest.",
  },
  {
    id: 6,
    title: "Elegant 3 BHK in Peaceful Locality",
    customPropertyName: "Peninsula Heights",
    projectName: "Peninsula Heights Tower B",
    city: "Mumbai",
    locality: "Andheri West",
    landmark: "Near Versova Metro",
    addressText: "Andheri West, Mumbai, Maharashtra 400061, India",
    coordinates: {
      lat: 19.11,
      lng: 72.875,
    },
    propertyType: "apartment",
    listingType: "sale",
    bedrooms: "3",
    bathrooms: "2",
    pricing: [
      {
        type: "asking_price",
        unit: "total",
        value: "28000000",
      },
    ],
    carpetArea: "1250",
    superArea: "1550",
    facing: "south",
    floorNumber: "10",
    totalFloors: "20",
    unitNumber: "1002",
    towerName: "B",
    furnishingStatus: "semi",
    possessionStatus: "ready",
    ageOfProperty: "4",
    ownershipType: "freehold",
    isGated: true,
    view: "city_view",
    mediaData: [
      {
        url: "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&h=600&fit=crop",
        type: "image",
        title: "Building Facade",
      },
      {
        url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
        type: "image",
        title: "Living Room",
      },
      {
        url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
        type: "image",
        title: "Bedroom",
      },
    ],
    features: [
      "swimming_pool",
      "gym",
      "children_play_area",
      "cctv_surveillance",
      "power_backup",
      "landscaped_gardens",
    ],
    amenities: [
      "balcony",
      "modular_kitchen",
      "study_room",
    ],
    developer: "PENINSULA LAND",
    verificationStatus: "VERIFIED",
    isPriceNegotiable: true,
    showMapExact: false,
    description:
      "Spacious 3 BHK apartment in peaceful neighborhood close to Versova beach and metro. Perfect for families.",
  },
];

// Locations data
export const LOCATIONS_DATA = [
  { name: "Andheri West", lat: 19.1136, lng: 72.8697 },
  { name: "Andheri East", lat: 19.1197, lng: 72.8478 },
  { name: "Kandivali West", lat: 19.2074, lng: 72.832 },
  { name: "Kandivali East", lat: 19.2083, lng: 72.8547 },
  { name: "Mahalaxmi", lat: 18.9826, lng: 72.8233 },
  { name: "Vikhroli", lat: 19.1107, lng: 72.9253 },
  { name: "Bandra West", lat: 19.0544, lng: 72.8181 },
  { name: "Bandra East", lat: 19.0591, lng: 72.8406 },
  { name: "Juhu", lat: 19.1075, lng: 72.8263 },
  { name: "Versova", lat: 19.1317, lng: 72.8103 },
  { name: "Powai", lat: 19.1197, lng: 72.9058 },
  { name: "Worli", lat: 19.0134, lng: 72.8177 },
  { name: "Lower Parel", lat: 19.0013, lng: 72.8267 },
  { name: "Dadar West", lat: 19.0189, lng: 72.8428 },
  { name: "Dadar East", lat: 19.0178, lng: 72.8478 },
  { name: "Malad West", lat: 19.1864, lng: 72.8365 },
  { name: "Malad East", lat: 19.1932, lng: 72.8489 },
  { name: "Goregaon West", lat: 19.1663, lng: 72.8526 },
  { name: "Goregaon East", lat: 19.1663, lng: 72.8697 },
  { name: "Borivali West", lat: 19.2307, lng: 72.8567 },
  { name: "Borivali East", lat: 19.2411, lng: 72.8611 },
];

// Virtual tours data
export const VIRTUAL_TOURS_DATA = [
  {
    id: 1,
    title: "SPACIOUS 3 BHK HOMES",
    price: "₹1.75 CR ONWARDS",
    location: "Andheri West",
    videoUrl: "https://www.youtube.com/shorts/974aaQLU4Ks",
    thumbnail:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=700&fit=crop",
  },
  {
    id: 2,
    title: "LUXURY APARTMENTS",
    price: "₹2.5 CR ONWARDS",
    location: "Kandivali West",
    videoUrl: "https://www.youtube.com/shorts/974aaQLU4Ks",
    thumbnail:
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&h=700&fit=crop",
  },
  {
    id: 3,
    title: "PREMIUM 4 BHK",
    price: "₹3.2 CR ONWARDS",
    location: "Mahalaxmi",
    videoUrl: "https://www.youtube.com/shorts/974aaQLU4Ks",
    thumbnail:
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&h=700&fit=crop",
  },
  {
    id: 4,
    title: "MODERN LIVING",
    price: "₹1.95 CR ONWARDS",
    location: "Vikhroli",
    videoUrl: "https://www.youtube.com/shorts/974aaQLU4Ks",
    thumbnail:
      "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=400&h=700&fit=crop",
  },
  {
    id: 5,
    title: "SEA VIEW VILLAS",
    price: "₹5.2 CR ONWARDS",
    location: "Mahalaxmi",
    videoUrl: "https://www.youtube.com/shorts/974aaQLU4Ks",
    thumbnail:
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=400&h=700&fit=crop",
  },
  {
    id: 6,
    title: "SMART HOMES",
    price: "₹2.8 CR ONWARDS",
    location: "Andheri West",
    videoUrl: "https://www.youtube.com/shorts/974aaQLU4Ks",
    thumbnail:
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&h=700&fit=crop",
  },
  {
    id: 7,
    title: "SPACIOUS 3 BHK HOMES",
    price: "₹1.75 CR ONWARDS",
    location: "Andheri West",
    videoUrl: "https://www.youtube.com/shorts/974aaQLU4Ks",
    thumbnail:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=700&fit=crop",
  },
  {
    id: 8,
    title: "LUXURY APARTMENTS",
    price: "₹2.5 CR ONWARDS",
    location: "Kandivali West",
    videoUrl: "https://www.youtube.com/shorts/974aaQLU4Ks",
    thumbnail:
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&h=700&fit=crop",
  },
  {
    id: 9,
    title: "PREMIUM 4 BHK",
    price: "₹3.2 CR ONWARDS",
    location: "Mahalaxmi",
    videoUrl: "https://www.youtube.com/shorts/974aaQLU4Ks",
    thumbnail:
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&h=700&fit=crop",
  },
  {
    id: 10,
    title: "MODERN LIVING",
    price: "₹1.95 CR ONWARDS",
    location: "Vikhroli",
    videoUrl: "https://www.youtube.com/shorts/974aaQLU4Ks",
    thumbnail:
      "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=400&h=700&fit=crop",
  },
  {
    id: 11,
    title: "SEA VIEW VILLAS",
    price: "₹5.2 CR ONWARDS",
    location: "Mahalaxmi",
    videoUrl: "https://www.youtube.com/shorts/974aaQLU4Ks",
    thumbnail:
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=400&h=700&fit=crop",
  },
  {
    id: 12,
    title: "SMART HOMES",
    price: "₹2.8 CR ONWARDS",
    location: "Andheri West",
    videoUrl: "https://www.youtube.com/shorts/974aaQLU4Ks",
    thumbnail:
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&h=700&fit=crop",
  },
];

// Trusted Developers Data
export const DEVELOPERS_DATA = [
  {
    id: 1,
    name: "Lodha Group",
    logo: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=200&h=200&fit=crop",
    projectsCount: 50,
    experience: "40+ Years",
    rating: 4.8,
    specialization: "Luxury Residential",
    completedProjects: 45,
    ongoingProjects: 5,
    description: "Leading real estate developer in Mumbai with iconic projects",
    locations: ["Mumbai", "Pune", "Bengaluru","Mumbai", "Pune", "Bengaluru","Mumbai", "Pune", "Bengaluru","Mumbai", "Pune", "Bengaluru","Mumbai", "Pune", "Bengaluru"],
    featured: true,
  },
  {
    id: 2,
    name: "Godrej Properties",
    logo: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=200&h=200&fit=crop",
    projectsCount: 85,
    experience: "25+ Years",
    rating: 4.7,
    specialization: "Premium Housing",
    completedProjects: 70,
    ongoingProjects: 15,
    description: "Trusted name in Indian real estate with sustainable projects",
    locations: ["Mumbai", "Pune", "Bengaluru", "NCR"],
    featured: true,
  },
  {
    id: 3,
    name: "Oberoi Realty",
    logo: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=200&h=200&fit=crop",
    projectsCount: 35,
    experience: "35+ Years",
    rating: 4.9,
    specialization: "Ultra Luxury",
    completedProjects: 28,
    ongoingProjects: 7,
    description: "Premium luxury developer known for excellence",
    locations: ["Mumbai", "Thane"],
    featured: true,
  },
  {
    id: 4,
    name: "Kolte Patil",
    logo: "https://images.unsplash.com/photo-1565402170291-8491f14678db?w=200&h=200&fit=crop",
    projectsCount: 60,
    experience: "30+ Years",
    rating: 4.6,
    specialization: "Mid-Premium Residential",
    completedProjects: 52,
    ongoingProjects: 8,
    description: "Quality homes with innovative designs",
    locations: ["Pune", "Bengaluru", "Mumbai"],
    featured: true,
  },
  {
    id: 5,
    name: "Prestige Group",
    logo: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=200&h=200&fit=crop",
    projectsCount: 280,
    experience: "35+ Years",
    rating: 4.7,
    specialization: "Mixed Use Development",
    completedProjects: 260,
    ongoingProjects: 20,
    description: "South India's leading property developer",
    locations: ["Bengaluru", "Chennai", "Hyderabad", "Goa"],
    featured: true,
  },
  {
    id: 6,
    name: "Tata Housing",
    logo: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=200&h=200&fit=crop",
    projectsCount: 40,
    experience: "20+ Years",
    rating: 4.8,
    specialization: "Affordable to Premium",
    completedProjects: 32,
    ongoingProjects: 8,
    description: "Part of the Tata legacy with quality assurance",
    locations: ["Mumbai", "Pune", "Bengaluru", "Gurugram"],
    featured: true,
  },
  {
    id: 7,
    name: "Mahindra Lifespaces",
    logo: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=200&h=200&fit=crop",
    projectsCount: 55,
    experience: "30+ Years",
    rating: 4.6,
    specialization: "Sustainable Living",
    completedProjects: 45,
    ongoingProjects: 10,
    description: "Creating sustainable communities and smart cities",
    locations: ["Mumbai", "Pune", "Chennai", "NCR"],
    featured: true,
  },
  {
    id: 8,
    name: "Brigade Group",
    logo: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=200&h=200&fit=crop",
    projectsCount: 75,
    experience: "35+ Years",
    rating: 4.7,
    specialization: "Residential & Commercial",
    completedProjects: 65,
    ongoingProjects: 10,
    description: "Bengaluru's leading integrated property developer",
    locations: ["Bengaluru", "Chennai", "Hyderabad", "Kochi"],
    featured: true,
  },
];
